spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: uAiqwVwjJ8-i
    url: jdbc:mysql://47.98.56.25/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console:  "%d - %msg%n"
##  path: C:\Users\11607\Desktop\log
#  file: C:\Users\11607\Desktop\log\sell.log